---
- hosts:  all
  become: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: install bind9
      apt: name=bind9 state=present
    - name: install apache2
      apt: name=apache2 state=present       
